---
# role-method: install
# description: Install our required packages for ansible-ntp

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install all required packages for ansible-ntp
  package:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ ntp_install_packages }}"

- name: Enable and start ntp
  service:
    name: ntp
    state: started
    enabled: yes
