---
# role-method: Handlers
# description: Run all of our handlers

- name: force_update
  service:
    name: ntp
    state: stopped
  notify: run_ntpdate
  when: ntp_install_force_update == true

- name: run_ntpdate
  command: "ntpdate {{ ntp_install_ntp_servers | first }}"
  when: ntp_install_force_update == true

- name: restart_ntp
  service:
    name: ntp
    state: restarted
